name: icomoon_selection_gen
description: A code generator for flutter that reads icomoon selection.json and generate the icon classes
version: 0.0.3
author: Gabriel Rohden
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.2.1
  build_config: ^1.0.0

dev_dependencies:
  meta: ^1.7.0
  recase: ^4.0.0
  dart_style: ^2.2.2
  code_builder: ^4.1.0
  build_runner: ^2.1.7
  build_test: ^2.1.5

